<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-07-12 06:06
=======
# Generated by Django 5.2.1 on 2025-07-11 13:22
>>>>>>> 21a7d23f69b639efa5db04719ce6db37e2f68067

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
