# Generated by Django 5.2.1 on 2025-07-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_delete_task'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.RenameField(
            model_name='task',
            old_name='prority',
            new_name='priority',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
